### PR TITLE
Improving main page

### PR DESCRIPTION
**Pull request by Drunken-Sailor7**
**Improves and updates index.html:**
- Adds new Scratch banner at the bottom
- Adds credits at the bottom
- Changes list to be unordered
- Removes unnecessary repetition of <center> tags/attributes
- Adds link to LLK GitHub page

**Improves CSS formatting through style.css:**
- Changes to nicer font
- Creates separate background and foreground colours
- Makes box and image responsive to screen width
- Improves padding and margins

**Other:**
- Creates new folder for assets for all images
- Uploaded bottom banner

### CODE REVIEW

**Review by R4356th — CHANGES_REQUESTED** [review]
Everything looks right but you seem to have left out HighFlyer222's name from the credits.

**Comment by Drunken-Sailor7** [comment]
My bad, I missed that, I've added that now.

**Review by R4356th — APPROVED** [review]
Looks good! Thanks for the changes. :)

**Comment by R4356th** [comment]
Merged! Thanks @Drunken-Sailor7!

**Comment by Drunken-Sailor7** [comment]
Thanks!

**Pull request merged**
